### ISSUE TITLE
Small naming error in Komodo's Figuramoji

### ISSUE THREAD

**Issue by SilverChimerawing** [FiguraMC/Assets#76]
![image](https://github.com/FiguraMC/Assets/assets/71190349/14fd4a0f-86bf-4f53-9758-b95226b89acf)
On the recent 1.21 Fabric build (posted in #dev-releases on June 15), this emoji is named `:komod:` instead of `:komodo:`

**Comment by circledeni** [comment]
https://github.com/FiguraMC/Assets/commit/1d37b3d33be98278596a06c477a82adb17e21e74
Done.
